# Kafka bootstrap server
spring.kafka.bootstrap-servers=${CC_BOOTSTRAP_SERVER}

# Kafka security
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${CC_API_KEY}" password="${CC_API_SECRET}";

# Schema registry
spring.kafka.properties.schema.registry.url=${CC_SCHEMA_REGISTRY_URL}
spring.kafka.properties.basic.auth.credentials.source=USER_INFO
spring.kafka.properties.schema.registry.basic.auth.user.info=${CC_SR_API_KEY}:${CC_SR_API_SECRET}

# serializers
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

# topic
topic.name=${CC_TOPIC}

# consumer
spring.kafka.consumer.group-id=vector-consumer-group-v2
spring.kafka.consumer.auto-offset-reset=latest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer

spring.kafka.properties.specific.avro.reader=true
enable-auto-commit=true