/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */
package com.rag.vector;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

/** Embedding vector message */
@org.apache.avro.specific.AvroGenerated
public class VectorEmbedding extends org.apache.avro.specific.SpecificRecordBase
        implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = 6813779187273913004L;

    public static final org.apache.avro.Schema SCHEMA$ =
            new org.apache.avro.Schema.Parser()
                    .parse(
                            "{\"type\":\"record\",\"name\":\"VectorEmbedding\",\"namespace\":\"com.rag.vector\",\"doc\":\"Embedding vector message\",\"fields\":[{\"name\":\"vector\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"Embedding vector\"}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static final SpecificData MODEL$ = new SpecificData();

    private static final BinaryMessageEncoder<VectorEmbedding> ENCODER =
            new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<VectorEmbedding> DECODER =
            new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     *
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<VectorEmbedding> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     *
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<VectorEmbedding> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link
     * SchemaStore}.
     *
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<VectorEmbedding> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this VectorEmbedding to a ByteBuffer.
     *
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a VectorEmbedding from a ByteBuffer.
     *
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a VectorEmbedding instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of
     *     this class
     */
    public static VectorEmbedding fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    /** Embedding vector */
    private java.util.List<java.lang.Float> vector;

    /**
     * Default constructor. Note that this does not initialize fields to their default values from
     * the schema. If that is desired then one should use <code>newBuilder()</code>.
     */
    public VectorEmbedding() {}

    /**
     * All-args constructor.
     *
     * @param vector Embedding vector
     */
    public VectorEmbedding(java.util.List<java.lang.Float> vector) {
        this.vector = vector;
    }

    @Override
    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    @Override
    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    @Override
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return vector;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    // Used by DatumReader.  Applications should not call.
    @Override
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                vector = (java.util.List<java.lang.Float>) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'vector' field.
     *
     * @return Embedding vector
     */
    public java.util.List<java.lang.Float> getVector() {
        return vector;
    }

    /**
     * Sets the value of the 'vector' field. Embedding vector
     *
     * @param value the value to set.
     */
    public void setVector(java.util.List<java.lang.Float> value) {
        this.vector = value;
    }

    /**
     * Creates a new VectorEmbedding RecordBuilder.
     *
     * @return A new VectorEmbedding RecordBuilder
     */
    public static com.rag.vector.VectorEmbedding.Builder newBuilder() {
        return new com.rag.vector.VectorEmbedding.Builder();
    }

    /**
     * Creates a new VectorEmbedding RecordBuilder by copying an existing Builder.
     *
     * @param other The existing builder to copy.
     * @return A new VectorEmbedding RecordBuilder
     */
    public static com.rag.vector.VectorEmbedding.Builder newBuilder(
            com.rag.vector.VectorEmbedding.Builder other) {
        if (other == null) {
            return new com.rag.vector.VectorEmbedding.Builder();
        } else {
            return new com.rag.vector.VectorEmbedding.Builder(other);
        }
    }

    /**
     * Creates a new VectorEmbedding RecordBuilder by copying an existing VectorEmbedding instance.
     *
     * @param other The existing instance to copy.
     * @return A new VectorEmbedding RecordBuilder
     */
    public static com.rag.vector.VectorEmbedding.Builder newBuilder(
            com.rag.vector.VectorEmbedding other) {
        if (other == null) {
            return new com.rag.vector.VectorEmbedding.Builder();
        } else {
            return new com.rag.vector.VectorEmbedding.Builder(other);
        }
    }

    /** RecordBuilder for VectorEmbedding instances. */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder
            extends org.apache.avro.specific.SpecificRecordBuilderBase<VectorEmbedding>
            implements org.apache.avro.data.RecordBuilder<VectorEmbedding> {

        /** Embedding vector */
        private java.util.List<java.lang.Float> vector;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         *
         * @param other The existing Builder to copy.
         */
        private Builder(com.rag.vector.VectorEmbedding.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.vector)) {
                this.vector = data().deepCopy(fields()[0].schema(), other.vector);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
        }

        /**
         * Creates a Builder by copying an existing VectorEmbedding instance
         *
         * @param other The existing instance to copy.
         */
        private Builder(com.rag.vector.VectorEmbedding other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.vector)) {
                this.vector = data().deepCopy(fields()[0].schema(), other.vector);
                fieldSetFlags()[0] = true;
            }
        }

        /**
         * Gets the value of the 'vector' field. Embedding vector
         *
         * @return The value.
         */
        public java.util.List<java.lang.Float> getVector() {
            return vector;
        }

        /**
         * Sets the value of the 'vector' field. Embedding vector
         *
         * @param value The value of 'vector'.
         * @return This builder.
         */
        public com.rag.vector.VectorEmbedding.Builder setVector(
                java.util.List<java.lang.Float> value) {
            validate(fields()[0], value);
            this.vector = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'vector' field has been set. Embedding vector
         *
         * @return True if the 'vector' field has been set, false otherwise.
         */
        public boolean hasVector() {
            return fieldSetFlags()[0];
        }

        /**
         * Clears the value of the 'vector' field. Embedding vector
         *
         * @return This builder.
         */
        public com.rag.vector.VectorEmbedding.Builder clearVector() {
            vector = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public VectorEmbedding build() {
            try {
                VectorEmbedding record = new VectorEmbedding();
                record.vector =
                        fieldSetFlags()[0]
                                ? this.vector
                                : (java.util.List<java.lang.Float>) defaultValue(fields()[0]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<VectorEmbedding> WRITER$ =
            (org.apache.avro.io.DatumWriter<VectorEmbedding>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<VectorEmbedding> READER$ =
            (org.apache.avro.io.DatumReader<VectorEmbedding>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override
    protected boolean hasCustomCoders() {
        return true;
    }

    @Override
    public void customEncode(org.apache.avro.io.Encoder out) throws java.io.IOException {
        long size0 = this.vector.size();
        out.writeArrayStart();
        out.setItemCount(size0);
        long actualSize0 = 0;
        for (java.lang.Float e0 : this.vector) {
            actualSize0++;
            out.startItem();
            out.writeFloat(e0);
        }
        out.writeArrayEnd();
        if (actualSize0 != size0)
            throw new java.util.ConcurrentModificationException(
                    "Array-size written was "
                            + size0
                            + ", but element count was "
                            + actualSize0
                            + ".");
    }

    @Override
    public void customDecode(org.apache.avro.io.ResolvingDecoder in) throws java.io.IOException {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            long size0 = in.readArrayStart();
            java.util.List<java.lang.Float> a0 = this.vector;
            if (a0 == null) {
                a0 =
                        new SpecificData.Array<java.lang.Float>(
                                (int) size0, SCHEMA$.getField("vector").schema());
                this.vector = a0;
            } else a0.clear();
            SpecificData.Array<java.lang.Float> ga0 =
                    (a0 instanceof SpecificData.Array
                            ? (SpecificData.Array<java.lang.Float>) a0
                            : null);
            for (; 0 < size0; size0 = in.arrayNext()) {
                for (; size0 != 0; size0--) {
                    java.lang.Float e0 = (ga0 != null ? ga0.peek() : null);
                    e0 = in.readFloat();
                    a0.add(e0);
                }
            }

        } else {
            for (int i = 0; i < 1; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        long size0 = in.readArrayStart();
                        java.util.List<java.lang.Float> a0 = this.vector;
                        if (a0 == null) {
                            a0 =
                                    new SpecificData.Array<java.lang.Float>(
                                            (int) size0, SCHEMA$.getField("vector").schema());
                            this.vector = a0;
                        } else a0.clear();
                        SpecificData.Array<java.lang.Float> ga0 =
                                (a0 instanceof SpecificData.Array
                                        ? (SpecificData.Array<java.lang.Float>) a0
                                        : null);
                        for (; 0 < size0; size0 = in.arrayNext()) {
                            for (; size0 != 0; size0--) {
                                java.lang.Float e0 = (ga0 != null ? ga0.peek() : null);
                                e0 = in.readFloat();
                                a0.add(e0);
                            }
                        }
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }
}
