/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */
package com.demo.schema;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

/** Sample schema to help you get started. */
@org.apache.avro.specific.AvroGenerated
public class UserQuestion extends org.apache.avro.specific.SpecificRecordBase
        implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = -415616186666043476L;

    public static final org.apache.avro.Schema SCHEMA$ =
            new org.apache.avro.Schema.Parser()
                    .parse(
                            "{\"type\":\"record\",\"name\":\"UserQuestion\",\"namespace\":\"com.demo.schema\",\"doc\":\"Sample schema to help you get started.\",\"fields\":[{\"name\":\"question\",\"type\":\"string\"}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static final SpecificData MODEL$ = new SpecificData();

    private static final BinaryMessageEncoder<UserQuestion> ENCODER =
            new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<UserQuestion> DECODER =
            new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     *
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<UserQuestion> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     *
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<UserQuestion> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link
     * SchemaStore}.
     *
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<UserQuestion> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this UserQuestion to a ByteBuffer.
     *
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a UserQuestion from a ByteBuffer.
     *
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a UserQuestion instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of
     *     this class
     */
    public static UserQuestion fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    private java.lang.CharSequence question;

    /**
     * Default constructor. Note that this does not initialize fields to their default values from
     * the schema. If that is desired then one should use <code>newBuilder()</code>.
     */
    public UserQuestion() {}

    /**
     * All-args constructor.
     *
     * @param question The new value for question
     */
    public UserQuestion(java.lang.CharSequence question) {
        this.question = question;
    }

    @Override
    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    @Override
    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    @Override
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return question;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    // Used by DatumReader.  Applications should not call.
    @Override
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                question = (java.lang.CharSequence) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'question' field.
     *
     * @return The value of the 'question' field.
     */
    public java.lang.CharSequence getQuestion() {
        return question;
    }

    /**
     * Sets the value of the 'question' field.
     *
     * @param value the value to set.
     */
    public void setQuestion(java.lang.CharSequence value) {
        this.question = value;
    }

    /**
     * Creates a new UserQuestion RecordBuilder.
     *
     * @return A new UserQuestion RecordBuilder
     */
    public static com.demo.schema.UserQuestion.Builder newBuilder() {
        return new com.demo.schema.UserQuestion.Builder();
    }

    /**
     * Creates a new UserQuestion RecordBuilder by copying an existing Builder.
     *
     * @param other The existing builder to copy.
     * @return A new UserQuestion RecordBuilder
     */
    public static com.demo.schema.UserQuestion.Builder newBuilder(
            com.demo.schema.UserQuestion.Builder other) {
        if (other == null) {
            return new com.demo.schema.UserQuestion.Builder();
        } else {
            return new com.demo.schema.UserQuestion.Builder(other);
        }
    }

    /**
     * Creates a new UserQuestion RecordBuilder by copying an existing UserQuestion instance.
     *
     * @param other The existing instance to copy.
     * @return A new UserQuestion RecordBuilder
     */
    public static com.demo.schema.UserQuestion.Builder newBuilder(
            com.demo.schema.UserQuestion other) {
        if (other == null) {
            return new com.demo.schema.UserQuestion.Builder();
        } else {
            return new com.demo.schema.UserQuestion.Builder(other);
        }
    }

    /** RecordBuilder for UserQuestion instances. */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder
            extends org.apache.avro.specific.SpecificRecordBuilderBase<UserQuestion>
            implements org.apache.avro.data.RecordBuilder<UserQuestion> {

        private java.lang.CharSequence question;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         *
         * @param other The existing Builder to copy.
         */
        private Builder(com.demo.schema.UserQuestion.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.question)) {
                this.question = data().deepCopy(fields()[0].schema(), other.question);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
        }

        /**
         * Creates a Builder by copying an existing UserQuestion instance
         *
         * @param other The existing instance to copy.
         */
        private Builder(com.demo.schema.UserQuestion other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.question)) {
                this.question = data().deepCopy(fields()[0].schema(), other.question);
                fieldSetFlags()[0] = true;
            }
        }

        /**
         * Gets the value of the 'question' field.
         *
         * @return The value.
         */
        public java.lang.CharSequence getQuestion() {
            return question;
        }

        /**
         * Sets the value of the 'question' field.
         *
         * @param value The value of 'question'.
         * @return This builder.
         */
        public com.demo.schema.UserQuestion.Builder setQuestion(java.lang.CharSequence value) {
            validate(fields()[0], value);
            this.question = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'question' field has been set.
         *
         * @return True if the 'question' field has been set, false otherwise.
         */
        public boolean hasQuestion() {
            return fieldSetFlags()[0];
        }

        /**
         * Clears the value of the 'question' field.
         *
         * @return This builder.
         */
        public com.demo.schema.UserQuestion.Builder clearQuestion() {
            question = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public UserQuestion build() {
            try {
                UserQuestion record = new UserQuestion();
                record.question =
                        fieldSetFlags()[0]
                                ? this.question
                                : (java.lang.CharSequence) defaultValue(fields()[0]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<UserQuestion> WRITER$ =
            (org.apache.avro.io.DatumWriter<UserQuestion>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<UserQuestion> READER$ =
            (org.apache.avro.io.DatumReader<UserQuestion>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override
    protected boolean hasCustomCoders() {
        return true;
    }

    @Override
    public void customEncode(org.apache.avro.io.Encoder out) throws java.io.IOException {
        out.writeString(this.question);
    }

    @Override
    public void customDecode(org.apache.avro.io.ResolvingDecoder in) throws java.io.IOException {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            this.question =
                    in.readString(this.question instanceof Utf8 ? (Utf8) this.question : null);

        } else {
            for (int i = 0; i < 1; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        this.question =
                                in.readString(
                                        this.question instanceof Utf8
                                                ? (Utf8) this.question
                                                : null);
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }
}
